install -Dm755 "./lansend" "/usr/local/bin/lansend"
install -Dm755 "./service" "/opt/LanSend/service"
install -Dm644 "./lansend.service" "/usr/lib/systemd/user/lansend.service"
install -Dm666 "./history.log" "/var/log/LanSend/history.log"
install -Dm666 "./config.json" "/etc/LanSend/config.json"

echo "Please run the following commands"
echo "systemctl --user daemon-reload"
echo "systemctl --user enable lansend"
echo "systemctl --user start lansend"
echo "LanSend files installed!"
